// src/components/character_creation/RaceSelection.vue
<template>
  <div class="race-selection-container">
    <div class="race-list">
      <button
        v-for="race in allRaceData"
        :key="race.key"
        class="race-button"
        :class="{ selected: character.race.key === race.key }"
        @click="handleSelectRace(race)"
      >
        {{ race.name }}
      </button>
    </div>

    <div class="race-details panel-details">
      <div class="character-identity">
        <div class="input-group">
          <label for="char-name">Name</label>
          <input id="char-name" type="text" :value="character.name" @input="updateName" />
        </div>
        <div class="input-group">
          <label>Geschlecht</label>
          <div class="gender-buttons">
            <button
              :class="{ selected: character.gender === 'Männlich' }"
              @click="emit('update-character', { gender: 'Männlich' })"
            >
              Männlich
            </button>
            <button
              :class="{ selected: character.gender === 'Weiblich' }"
              @click="emit('update-character', { gender: 'Weiblich' })"
            >
              Weiblich
            </button>
          </div>
        </div>
      </div>
      <div class="details-divider"></div>

      <h2>{{ character.race.name }}</h2>
      <div class="details-divider"></div>

      <h3>Attributs-Boost</h3>
      <p>{{ character.race.ability_bonuses.text }}</p>

      <ul v-if="floatingBonuses.length > 0" class="ability-bonus-list">
        <li v-for="abiKey in ABILITIES" :key="abiKey">
          <span>{{ abiKey.toUpperCase() }}</span>
          <div class="bonus-buttons">
            <button
              v-for="(bonusValue, index) in floatingBonuses"
              :key="index"
              @click="handleAssignBonus(abiKey, bonusValue)"
              :class="{ selected: assignments[abiKey] === bonusValue }"
              :disabled="assignments[abiKey] && assignments[abiKey] !== bonusValue"
            >
              +{{ bonusValue }}
            </button>
          </div>
        </li>
      </ul>
    </div>
  </div>
</template>

<script setup>
import { ref, watch } from 'vue'
import allRaceData from '../../data/races.json'

const ABILITIES = ['str', 'dex', 'con', 'int', 'wis', 'cha']

const props = defineProps({
  character: { type: Object, required: true },
})

const emit = defineEmits(['update-character'])

// Lokaler State nur für die Bonus-Zuweisung
const assignments = ref(props.character.ability_bonus_assignments || {})
const floatingBonuses = ref(props.character.race.ability_bonuses.floating || [])

// `watch` ist das Vue-Pendant zu `useEffect` mit Abhängigkeiten.
// Dieser Code wird immer dann ausgeführt, wenn sich `props.character.race` ändert.
watch(
  () => props.character.race,
  (newRace) => {
    let initialAssignments = newRace.ability_bonuses.fixed || {}
    assignments.value = initialAssignments
    floatingBonuses.value = newRace.ability_bonuses.floating || []

    // Wichtig: Beim Rassenwechsel Subrace und Ancestry zurücksetzen
    emit('update-character', {
      race: newRace,
      ability_bonus_assignments: initialAssignments,
      subrace: null,
      ancestry: null,
    })
  },
)

const handleSelectRace = (race) => {
  // Wenn die Rasse bereits ausgewählt ist, nichts tun
  if (props.character.race.key === race.key) return

  // Die Änderung wird über den watch-Hook oben verarbeitet, der dann das Event auslöst
  // Wir können aber auch direkt hier das Event auslösen, um die race sofort zu aktualisieren
  emit('update-character', { race })
}

const handleAssignBonus = (ability, bonus) => {
  const currentAssignments = { ...assignments.value }

  // Bonus entfernen, falls er schon woanders zugewiesen war
  const oldAbilityForBonus = Object.keys(currentAssignments).find(
    (key) => currentAssignments[key] === bonus,
  )
  if (oldAbilityForBonus) {
    delete currentAssignments[oldAbilityForBonus]
  }

  // Bonus zuweisen oder entfernen (Toggle)
  if (currentAssignments[ability] === bonus) {
    delete currentAssignments[ability]
  } else {
    currentAssignments[ability] = bonus
  }

  assignments.value = currentAssignments
  emit('update-character', { ability_bonus_assignments: currentAssignments })
}

const updateName = (event) => {
  emit('update-character', { name: event.target.value })
}
</script>

<style scoped>
/* Hier den Inhalt von RaceSelection.css UND PanelDetails.css einfügen */
/* RaceSelection.css */
.race-selection-container {
  display: flex;
  height: 100%;
  gap: 20px;
}
.race-list {
  display: flex;
  flex-direction: column;
  flex-basis: 30%;
  gap: 5px;
}
.race-button {
  width: 100%;
  padding: 15px;
  background-color: transparent;
  border: 1px solid #4a4a4a;
  color: #fff;
  font-size: 1.1em;
  text-align: left;
  cursor: pointer;
  transition:
    background-color 0.2s,
    border-color 0.2s;
}
.race-button:hover {
  background-color: #3a3a3a;
  border-color: #c7a25a;
}
.race-button.selected {
  border-left: 3px solid #c7a25a;
  background-color: rgba(168, 126, 76, 0.2);
  font-weight: bold;
}
.race-details {
  flex-basis: 70%;
  padding-left: 20px;
  border-left: 1px solid #4a4a4a;
}

/* PanelDetails.css (Auszug) */
.panel-details h2 {
  color: #c7a25a;
  margin-top: 0;
}
.details-divider {
  border-bottom: 1px solid #4a4a4a;
  margin: 15px 0;
}
.ability-bonus-list {
  list-style: none;
  padding: 0;
}
.ability-bonus-list li {
  display: flex;
  justify-content: space-between;
  align-items: center;
  padding: 8px 0;
  border-bottom: 1px solid #4a4a4a;
}
.bonus-buttons {
  display: flex;
  gap: 5px;
}
.bonus-buttons button {
  background-color: #4a4a4a;
  border: 1px solid #3a3a3a;
  color: #fff;
  padding: 4px 8px;
  cursor: pointer;
}
.bonus-buttons button.selected {
  background-color: #c7a25a;
  border-color: #fff;
}
.bonus-buttons button:disabled {
  background-color: #333;
  cursor: not-allowed;
  opacity: 0.5;
}
.character-identity {
  display: flex;
  gap: 20px;
  margin-bottom: 20px;
}
.input-group {
  flex: 1;
}
.input-group label {
  display: block;
  margin-bottom: 5px;
  font-size: 0.9em;
}
.input-group input,
.gender-buttons {
  width: 100%;
}
.gender-buttons {
  display: flex;
}
.gender-buttons button {
  flex: 1; /* ...weitere Stile... */
}
.gender-buttons button.selected {
  background-color: #c7a25a;
}
</style>

// src/components/character_creation/RaceSelection.jsx
// src/components/character_creation/RaceSelection.js
import React, { useState, useEffect } from 'react';
import './RaceSelection.css';
import './PanelDetails.css';
import allRaceData from '../../data/races.json';
import './CreationSidebar.css'; 

const ABILITIES = ['str', 'dex', 'con', 'int', 'wis', 'cha'];

export const RaceSelection = ({ character, updateCharacter }) => {
  const [assignments, setAssignments] = useState({});
  const selectedRace = character.race;
  const selectedSubrace = character.subrace;
  const selectedAncestry = character.ancestry; // NEU

  useEffect(() => {
    // Bei Rassenwechsel die Zuweisungen zurücksetzen
    let initialAssignments = {};
    
    if (selectedRace.ability_bonuses.fixed) {
      Object.entries(selectedRace.ability_bonuses.fixed).forEach(([ability, value]) => {
        initialAssignments[ability] = (initialAssignments[ability] || 0) + value;
      });
    }

    // floatingBonuses hier direkt aus selectedRace holen
    const floatingBonuses = selectedRace.ability_bonuses.floating || [];
    
    if (floatingBonuses.length > 0) {
      // Wenn es floating Boni gibt, initialisiere 'available'
      initialAssignments.available = floatingBonuses.map((val, idx) => ({ index: idx, value: val, assignedTo: null }));
    }
    
    setAssignments(initialAssignments);
  
  }, [selectedRace]); // Nur selectedRace als Dependency


  const onSelectRace = (race) => {
    // Beim Wechsel des Volks müssen wir die Zuweisungen zurücksetzen
    updateCharacter({ 
      race: race, 
      subrace: null,
      ancestry: null,
      ability_bonus_assignments: race.ability_bonuses.fixed || {},
      floating_bonus_assignments: {} 
    });
  };

  // Handler für die Auswahl der Unterart
  const onSelectSubrace = (subrace) => {
    updateCharacter({ subrace: subrace });
  };

  // *** NEU: Handler für die Auswahl der Abstammung ***
  const onSelectAncestry = (ancestry) => {
    updateCharacter({ ancestry: ancestry });
  };


  const handleAssignBonus = (abiKey, index) => {
    setAssignments(prev => {
      const newFloating = { ...prev.floating_bonus_assignments };
      const currentAssignment = newFloating[abiKey];
      
      if (currentAssignment === index) {
        // Zuweisung aufheben
        delete newFloating[abiKey];
      } else {
        // Zuweisung ändern oder neu setzen
        // Entferne zuerst, falls dieser Bonus (index) woanders zugewiesen war
        for (const key in newFloating) {
          if (newFloating[key] === index) {
            delete newFloating[key];
          }
        }
        // Setze die neue Zuweisung
        newFloating[abiKey] = index;
      }
      
      // Update des Character-Objekts im Haupt-State
      updateCharacter({ floating_bonus_assignments: newFloating });

      return {
        ...prev,
        floating_bonus_assignments: newFloating
      };
    });
  };

  const isBonusAssigned = (abiKey, index) => {
    return assignments.floating_bonus_assignments?.[abiKey] === index;
  };

  const isBonusUsed = (index) => {
    return Object.values(assignments.floating_bonus_assignments || {}).includes(index);
  };

  if (!selectedRace) {
    return <div>Lade Völker...</div>;
  }
  
  // floatingBonuses hier für die Render-Logik definieren
  const floatingBonuses = selectedRace.ability_bonuses.floating || [];
  
  // *** NEU: Logik für den Detail-Titel ***
  const getDetailTitle = () => {
    if (selectedSubrace) return selectedSubrace.name;
    if (selectedAncestry) return `${selectedRace.name} (${selectedAncestry.name})`;
    return selectedRace.name;
  };

  // *** NEU: Logik für die Detail-Beschreibung ***
  const getDetailDescription = () => {
    // Untervölker (wie Hochelf) haben eigene Beschreibungen
    if (selectedSubrace) return selectedSubrace.description;
    // Abstammungen (wie Roter Drache) haben keine, also die des Hauptvolks verwenden
    return selectedRace.description;
  };


  return (
    <div className="race-panel-layout">
      
      {/* --- LINKE SPALTE (Völkerliste) --- */}
      <div className="race-column-left">
        <div className="race-box">
          <h3>Völker</h3>
          
          <div className="race-list">
            {allRaceData.map(race => (
              <React.Fragment key={race.key}>
                <button
                  className={`race-button ${selectedRace.key === race.key ? 'selected' : ''}`}
                  onClick={() => onSelectRace(race)}
                >
                  {race.name}
                </button>

                {/* --- Collapsible Container (Logik angepasst) --- */}
                {selectedRace.key === race.key && (
                  <>
                    {/* Fall 1: Untervölker (z.B. Elf) */}
                    {race.subraces && race.subraces.length > 0 && (
                      <div className="subrace-collapsible-container">
                        {race.subraces.map(subrace => (
                          <button
                            key={subrace.key}
                            className={`subrace-button-nested ${selectedSubrace?.key === subrace.key ? 'selected' : ''}`}
                            onClick={() => onSelectSubrace(subrace)}
                          >
                            {subrace.name}
                          </button>
                        ))}
                      </div>
                    )}

                    {/* Fall 2: Abstammungen (z.B. Drachenblütiger) */}
                    {race.ancestries && race.ancestries.length > 0 && (
                      <div className="subrace-collapsible-container">
                        {race.ancestries.map(ancestry => (
                          <button
                            key={ancestry.key}
                            className={`subrace-button-nested ${selectedAncestry?.key === ancestry.key ? 'selected' : ''}`}
                            onClick={() => onSelectAncestry(ancestry)}
                          >
                            {ancestry.name}
                          </button>
                        ))}
                      </div>
                    )}
                  </>
                )}
                {/* --- Ende Collapsible Container --- */}

              </React.Fragment>
            ))}
          </div>
        </div>
      </div>

      {/* --- RECHTE SPALTE (Details) --- */}
      <div className="race-column-right">
        <div className="race-box">
          <h2 className="panel-details-header">{getDetailTitle()}</h2>

          <div className="race-details-content-wrapper">
            <p className="panel-details-description">
              {getDetailDescription()}
            </p>
            
            <div className="details-divider"></div>

            {/* Zeige immer die Boni des Hauptvolks */}
            <h3>Attributs-Boost</h3>
            <p>{selectedRace.ability_bonuses.text}</p>
            
            {floatingBonuses.length > 0 && (
              <ul className="ability-bonus-list">
                {ABILITIES.map(abiKey => (
                  <li key={abiKey}>
                    <span>{abiKey.toUpperCase()}</span>
                    <div className="bonus-buttons">
                      {floatingBonuses.map((bonusValue, index) => (
                        <button
                          key={`${abiKey}-${index}`}
                          onClick={() => handleAssignBonus(abiKey, index)}
                          className={isBonusAssigned(abiKey, index) ? 'selected' : ''}
                          disabled={isBonusUsed(index) && !isBonusAssigned(abiKey, index)}
                        >
                          +{bonusValue}
                        </button>
                      ))}
                    </div>
                  </li>
                ))}
              </ul>
            )}

            {/* *** Zeige die Traits (Merkmale) an (Logik angepasst) *** */}
            <div className="details-divider"></div>
            <h3>Merkmale</h3>
            <ul className="traits-list-panel">
              {/* Zeige die Merkmale des Hauptvolks (außer Odemwaffe, die wird ersetzt) */}
              {selectedRace.traits
                .filter(trait => !(selectedRace.key === 'dragonborn' && trait.name === 'Odemwaffe'))
                .map(trait => (
                 <li key={trait.name}>
                    <strong>{trait.name}:</strong> {trait.description}
                  </li>
              ))}
              
              {/* Zeige die Merkmale des Untervolks, falls ausgewählt */}
              {selectedSubrace && selectedSubrace.traits.map(trait => (
                 <li key={trait.name}>
                    <strong>{trait.name} ({selectedSubrace.name}):</strong> {trait.description}
                  </li>
              ))}

              {/* Zeige die Merkmale der Abstammung, falls ausgewählt */}
              {selectedRace.key === 'dragonborn' && selectedAncestry && (
                <>
                  <li>
                    <strong>Schadensresistenz ({selectedAncestry.name}):</strong> Du hast Resistenz gegen {selectedAncestry.damage_type}.
                  </li>
                  <li>
                    <strong>Odemwaffe ({selectedAncestry.name}):</strong> {selectedAncestry.breath_weapon} ({selectedAncestry.damage_type}).
                  </li>
                </>
              )}
            </ul>

          </div> 
        </div>
      </div>
    </div>
  );
};
